### ISSUE TITLE
Whats New page in Japanese is broken

### ISSUE THREAD

**Issue by lewip** [NetAppDocs/cloudinsights.ja-jp#1]
### Page URL

https://docs.netapp.com/ja-jp/cloudinsights/concept_whats_new.html

### Page title

Cloud Insights whats new in Japanese

### Summary

Hi there, the page is not readable when changed to Japanese language.
Could you please fix this, thank you!

<img width="1673" alt="image" src="https://github.com/NetAppDocs/cloudinsights.ja-jp/assets/92243422/6ad1093d-320f-4148-be24-4e727a6d3809">

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by ntap-bmegan** [comment]
It's only JA, not any other language. 

An interesting thing is that the page is not in the left sidebar in any language, including English. But since that matches across languages, I don't think it's a loc issue. (Just a content standard issue.)

Showing French:

![image](https://github.com/NetAppDocs/cloudinsights.ja-jp/assets/56453501/17cff789-cbd7-4691-971e-49808a563264)

Also, unrelated, the mini-toc displays on loc pages, which is A Different Thing Entirely. 

I'll take a look at the JA Adoc file.

**Comment by akseldavis** [comment]
@ntap-bmegan It only seems to be occurring with the Japanese What's New file. I see that the repository is still tracking a file that was removed from English: https://github.com/NetAppDocs/cloudinsights.ja-jp/blob/main/concept_whats_new.adoc.orig which shares the same permalink. 

I'd recommend us deleting the file, repo contents, or repo and re-building with latest from EN. If it is still an issue, then likely that it is stuck in the Japanese TM and needs GPSO systems to intervene.

**Comment by ntap-bmegan** [comment]
This has been corrected and the page displays normally now. 

From my system:

![image](https://github.com/NetAppDocs/cloudinsights.ja-jp/assets/56453501/0e0818dd-9493-4d4b-84d7-649d74461b31)
